### ISSUE TITLE
Get length of Intro/Outro direct from AAX

### ISSUE THREAD

**Issue by elvquant** [rmcrackan/inAudible#1]
I'm not sure, but it seems the Audible Intro/Outro are fixed values in your program. The time length of Audible Into/Outro can find directly in AAX file at tag "moov.trak.mdia.minf.stbl.stsd.aavd.aabd". There are length information for chapter+2 time data.
The type of the time slice can be TITLE_INTRO (1), TITLE_OUTRO(2), MAIN_INTRO(3), MAIN_OUTRO(4) and MAIN_AUDIO(5), size are in milliseconds.

You can get the data for more accurate skipping the into/outro-part of the audiobook.

Please add the feature to the macOS version, too. Thanks from a macie!

See a python script below to get the data from AAX:
```
#!/usr/bin/env python

import os
import sys
import struct

BLOCK_SIZE = 0x120

MAIN_AUDIO = 5
MAIN_INTRO = 3
MAIN_OUTRO = 4
TITLE_INTRO = 1
TITLE_OUTRO = 2

def aabdInfo(fp):
    (offset,aabdLen) = findAtom(fp,0,"moov.trak.mdia.minf.stbl.stsd.aavd.aabd")
    fp.seek(offset + 12) 
    num = struct.unpack("!i", fp.read(4))[0]
    print "Number of blocks: %d" % num
    lengths = [0,0,0,0,0,0] 
    base = offset + 20
    for i in range(0, num):
        fp.seek(base + i * BLOCK_SIZE)
        (bsize, btrack, btag ,btype) = struct.unpack("!iiii", fp.read(16))
        # track should always be 1 and tag is 'aavd'
        if btrack == 1 and btag == 0x61617664:
            lengths[btype] += bsize
    # main intro and outro is needed for multipart audiobooks
    skipBeg = (lengths[TITLE_INTRO] + lengths[MAIN_INTRO]) / 1000.0
    skipEnd = (lengths[TITLE_OUTRO] + lengths[MAIN_OUTRO]) / 1000.0
    bookLen = lengths[MAIN_AUDIO] / 1000.0
    print "INTRO: %.3f , OUTRO: %.3f , AUDIO: %.3f" % (skipBeg,skipEnd,bookLen)
    return (skipBeg, skipEnd, bookLen)

if __name__=="__main__":
    if len(sys.argv) != 2:
        sys.exit("Using " + sys.argv[0] + " <filename>")

    in_file = sys.argv[1]
    fp = open(in_file, "rb")
    beg, end, len = aabdInfo(fp)
    fp.close()
```

**Comment by rmcrackan** [comment]
Sorry, I didn't create inAudible and I don't provide support. It's available here for download as a courtesy because some people don't feel good about getting it from torrent sites. The author gave me permission to host the installers here. Frankly it's incredibly outdated (latest is Aug 12 2017). I recommend other [more recent software](https://github.com/rmcrackan/AudiobookHub#backup-decrypt-convert-organize)
