### ISSUE TITLE
Windows Installer infected with virus

### ISSUE THREAD

**Issue by DavidStrickland0** [rmcrackan/inAudible#3]

**Comment by robwoodok** [comment]
I got the same thing from Avast.  It just says Malware General, so it could be a false positive

**Comment by DavidStrickland0** [comment]
Installed from another source and didnt get the Virus warning. Coupled with the fact that there is no code for this installer and all your downloading is a zip I'm going to have to say that there's likely very little thats "false" about the positive.... but aint worth it to me to look any further.. 
Caveat emptor

**Comment by Darthagnon** [comment]
Probably a false positive - hack tools like this are usually detected as malicious by antiviruses

**Comment by EarthBoundX5** [comment]
Given that the files have not been updated in 3 years, I'm going to guess they have not been adjusted.

VirusTotal reports nothing unusual, even rescanned and scanned zip / msi separate.  Only the A/V mentioned here say it's a threat....Avast, AVG, and...McAfee...so totally ignorable...

https://www.virustotal.com/gui/file/6c4a04fa76a1e7540cd9707051d21db903715b61783b3ab46b9abeec13865526/detection

https://www.virustotal.com/gui/file/1e0c464a4631818e81c7f893054e3fcc3509e2c15657c0da9cef01930f22ecdb/detection
